apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jenkins
spec:
  selector:
    mathcLabels:
      app: jenkins
  replicas: 3
  template:
    metadata:
      name: jenkins-pod
      labels:
        app: jenkins
    spec:
      container:
        - name: jenkins
          image: jenkins:2.60.3
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          emptyDir: {}



